//! Adapted from code generated by Knurling app template.

#![no_std]
#![no_main]

// memory layout + panic handler
use stm32f4d as _;

// See https://crates.io/crates/defmt-test/0.3.0 for more documentation (e.g. about the 'state'
// feature)
#[defmt_test::tests]
mod tests {
    use defmt::assert;

    #[test]
    fn it_works() {
        assert!(true)
    }
}
