//! Adapted from code generated by Knurling app template.

#![no_main]
#![no_std]

// global logger + panicking-behavior + memory layout
use stm32f4d as _;

#[cortex_m_rt::entry]
fn main() -> ! {
    // try setting the DEFMT_LOG environment variable
    // e.g. `export DEFMT_LOG=info` or `DEFMT_LOG=trace cargo rb levels`
    defmt::info!("info");
    defmt::trace!("trace");
    defmt::warn!("warn");
    defmt::debug!("debug");
    defmt::error!("error");

    stm32f4d::exit()
}
